Fix issue with C++ endf float converter
paulromano/endf-python pull request #7
Opened 2024-04-17 08:58 UTC by aidancrilly

This closes #6 - at least for me, I noticed someone having similar issues in #4.

The crash seems to be a seg fault that occurs when the endf float being converted is negative, i.e. has a leading minus sign.

Positive numbers have leading whitespace so hit the continue statement and j is not incremented. Therefore, the first digit is placed at arr[1]. However, negative numbers had the leading minus sign placed at arr[1] and first digit at arr[2]. This means when the null terminator is placed at the end, for negative numbers this is at arr[12] so the crash occurs.

This would seem to me to be an issue across systems.

2024-04-17 14:14 UTC, paulromano commented
Thanks @aidancrilly! Can you give a specific example of an 11-character string that triggers the problem?

2024-04-17 14:38 UTC, aidancrilly commented
@paulromano 
Sure, in ENDF/B-VIII.0 incident neutron data for deuterium there is -2.225002+6 at the beginning of the MF = 3, MT = 16 record. This is the QM/QI value.

2024-04-18 12:06 UTC, paulromano requested changes
Thanks again! Just one small request:

2024-04-18 12:06 UTC, paulromano commented on src/endf/_records.cpp
> +    if (std::isspace(c)) continue;
The ENDF format actually does not allow characters like `\t` and `\f` which are handled by `std::isspace`. Sticking with the original check against a space should be sufficient.

2024-04-18 14:07 UTC, paulromano approved these changes

2024-04-18 14:07 UTC, merged

2024-04-18 14:10 UTC, paulromano commented
@aidancrilly Would you be up for making a similar PR to [OpenMC](https://github.com/openmc-dev/openmc)? The `cfloat_endf` function was originally borrowed from there:
https://github.com/openmc-dev/openmc/blob/develop/openmc/data/endf.c

It would be good to also add the example you mentioned (-2.225002+6) to the tests here:
https://github.com/openmc-dev/openmc/blob/develop/tests/unit_tests/test_endf.py